### ISSUE TITLE
Your updates module for waybar is way out-of-date

### ISSUE THREAD

**Issue by dogknowsnx** [arnavgr/dotfiles#1]
If you're still using this setup I'd recommend updating the module for Arch Linux package updates (although unmaintained now), mainly because a lot of optimizations had been introduced later on...

**Comment by arnavgr** [comment]
> If you're still using this setup I'd recommend updating the module for Arch Linux package updates (although unmaintained now), mainly because a lot of optimizations had been introduced later on...

yup im yet to work on it, im not on arch as of now but ill update it as soon as i get back. Thanks
